version: "3.8"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - 8000:8000
    volumes:
      - .:/app
      - /app/node_modules
#     networks:
#       - strapi

# networks:
#   strapi:
#     name: Strapi
#     driver: bridge